version: '3'
services:
  postgres:
    image: postgres:9.6-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: postgres-order
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
    ports:
      - "5433:5432"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9093:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka-data:/var/run/docker.sock
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
volumes:
  postgres-data:
  kafka-data: