apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "order.fullname" . }}
  labels:
  {{- include "order.labels" . | nindent 4 }}
data:
  application.yaml: |-
    {{- if .Values.configmap }}
    {{- .Values.configmap | nindent 4 }}
  {{- end }}