apiVersion: v1
kind: Service
metadata:
  name: order
spec:
  selector:
    app: order
    deploymentconfig: order-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
---
apiVersion: v1
kind: Route
metadata:
  labels:
    app: order
  name: order
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: order
    weight: 100