name: Order CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Coding standards
        run: |
          ./gradlew checkStyleMain
          ./gradlew pmdMain
      - name: Unit test
        run: ./gradlew test
      - name: Integration test
        run: ./gradlew integrationTest
      - name: OWASP Dependency check
        run: ./gradlew dependencyCheckAggregate
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.2
        with:
          projectBaseDir: api-service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Build
        run: ./gradlew build
