name: Order CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Coding standard
        run: |
          ./gradlew checkStyleMain
          ./gradlew pmdMain
      - name: Unit test
        run: ./gradlew test
      - name: Integration test
        run: ./gradlew integrationTest
      - name: Build
        run: ./gradlew build
